name: Using Database with environment variables

on: 
  push:
    branches:
      - main

jobs:
  build:
    env:
      DB_USER: test
      DB_PASSWORD: test123
      DB_NAME: testing
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: $DB_USER
          POSTGRES_PASSWORD: $DB_PASSWORD
          POSTGRES_DB: $DB_NAME
        ports:
          - 5432:5432

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Install PostgreSQL Client
      run: sudo apt-get install -y postgresql-client

    - name: Wait for PostgreSQL to be ready
      run: |
        until pg_isready -h localhost -p 5432; do
          sleep 1
        done

    - name: Create Table and Insert Data
      run: |
        PGPASSWORD=$DB_PASSWORD psql -h localhost -U $DB_USER -d $DB_NAME -c "CREATE TABLE users (id SERIAL PRIMARY KEY, name VARCHAR(50));"
        PGPASSWORD=$DB_PASSWORD psql -h localhost -U $DB_USER -d $DB_NAME -c "INSERT INTO users (name) VALUES ('Alice'), ('Bob');"

    - name: Query Data
      run: |
        PGPASSWORD=$DB_PASSWORD psql -h localhost -U $DB_USER -d $DB_NAME -c "SELECT * FROM users;"
