name: Example

on:
  push:

jobs:
  job-with-mysql-8_0:
    runs-on: ubuntu-20.04
    env:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: foo
      MYSQL_USER: user1
      MYSQL_PASSWORD: user1_password
      NEW_DATABASE: new_db
    services:
      db:
        image: mysql:8.0
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: ${{ env.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ env.MYSQL_DATABASE }}
          MYSQL_USER: ${{ env.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ env.MYSQL_PASSWORD }}
        options: >-
          --health-cmd "mysqladmin ping"
          --health-interval 10s
          --health-timeout 5s
